name: form
description: A new Flutter project.


publish_to:


version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  firebase_core: ^1.10.5
  firebase_auth: ^3.3.3
  cloud_firestore: ^3.1.4
  shared_preferences: ^2.0.11
  google_sign_in: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true



